services:
  - type: web
    name: wedding-invite
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true
    region: Dublin  # pode mudar p/ o mais próximo de ti (ex: oregon, singapore)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
